name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions on ${{ github.repository }}
on: [push]
jobs:
  first-claudia-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env: 
          SUPER_SECRET: ${{ secrets.SECRET }}
        run: echo "$SUPER_SECRET" > ./secrets.txt
      - run: aws configure import --csv file://secrets.txt
      - run: npm install -g claudia
      - run: aws configure list-profiles
      - run: aws configure list
      - run: export AWS_PROFILE=backend-migration
      - run: claudia create --region us-west-1 --handler lambda.handler 
  update-claudia:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g claudia
      - run: claudia update
      - name: test to make sure working
        run: claudia test-lambda
