name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions on ${{ github.repository }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo ${{ github.repository }}
      - shell: bash
        env: 
          SUPER_SECRET: ${{ secrets.SECRET }}
        run: echo "$SUPER_SECRET" > ./secrets.txt
      - run: aws configure import --csv file://secrets.txt
      - name: verify profile correctly imported
        run: aws configure list-profiles